openapi: 3.0.2
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              anyOf: [
                      {'$ref': '#/components/schemas/PetByAge'},
                      {'$ref': '#/components/schemas/PetByType'}
                    ]
      responses:
        '200':
          description: OK
          content: 
              application/json:
                schema:
                  oneOf:
                        [ 
                          {'$ref' : '#/components/schemas/PetByAge'},
                          {'$ref' : '#/components/schemas/PetByType'}
                        ]
                
components:
  schemas:
    PetByAge:
      type: object
      properties: 
        age: 
          type: integer
        nickname: 
          oneOf:
                        [ 
                          {'$ref' : '#/components/schemas/PetByAge'},
                          {'$ref' : '#/components/schemas/PetByType'}
                        ]
      required:
        - age
      example: 
        age: 12
        nickname: ram
          
    PetByType:
      type: object
      properties:
        pet_type:
          type: string
          enum: [Cat, Dog]
        hunts:
          type: boolean
      required: 
        - pet_type
      example: 
        pet_type: Cat
        hunts: true
        
        
        
        
        
