openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  '/api/v1/dependant/{_uid}/':
    get:
      operationId: retrieveDependant
      parameters:
        - name: _uid
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dependant'
          description: ''
    put:
      operationId: updateDependant
      parameters:
        - name: _uid
          in: path
          required: true
          description: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dependant'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dependant'
          description: ''
components:
  schemas:
    Dependant:
      properties:
        _uid:
          type: string
          title: ' uid'
          readOnly: true
        name:
          type: string
          title: Dependant name
        property:
          allOf:
            - title: Dependence property title
              description: Dependence property description
            - $ref: '#/components/schemas/Dependence'
      required:
        - name
      title: Dependant title
      description: Dependant description
    Dependence:
      properties:
        _uid:
          type: string
          title: ' uid'
          readOnly: true
        name:
          type: string
          title: Dependence name
      required:
        - name
      title: Dependence title
      description: Dependence description

