swagger: '2.0'
info:
  description: |
    Powerful collaboration, code review, and code management for open source and private projects.
  title: GitHub
  version: v3

securityDefinitions:
  oauth_2_0:
    authorizationUrl: 'https://github.com/login/oauth/authorize'
    description: |
      OAuth2 is a protocol that lets external apps request authorization to private
      details in a user's GitHub account without getting their password. This is
      preferred over Basic Authentication because tokens can be limited to specific
      types of data, and can be revoked by users at any time.
    flow: accessCode
   
    tokenUrl: 'https://github.com/login/oauth/access_token'
    type: oauth2
paths:
  /emojis:
    get:
      description: Lists all the emojis available to use on GitHub.
      parameters:
        - description: |
            You can check the current version of media type in responses.
          in: header
          name: X-GitHub-Media-Type
          type: string
        - description: Is used to set specified media type.
          in: header
          name: Accept
          type: string
        - in: header
          name: X-RateLimit-Limit
          type: integer
        - in: header
          name: X-RateLimit-Remaining
          type: integer
        - in: header
          name: X-RateLimit-Reset
          type: integer
        - in: header
          name: X-GitHub-Request-Id
          type: integer
      responses:
        '200':
          description: OK
        '403':
          description: |
            API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
            for details.
